### ISSUE TITLE
Uncaught ReferenceError: hm is not defined (Gutenberg 3.7)

### ISSUE THREAD

**Issue by nicolairobles** [humanmade/hm-gutenberg-tools#35]
In using PostControls, the below no longer works with Gutenberg 3.7

`const { PostControl } = hm.controls;`

**Comment by attcn** [comment]
This would be great to have working in 3.7!  I hope this gets some traction.

**Comment by rafal-sokolowski** [comment]
Confirmed.

From the console:
`TypeError: i is not a function editor.bundle.js:11:36538`

As a consequence:
`ReferenceError: hm is not defined` in blocks.build.js

**Comment by mattheu** [comment]
Ah yes this is a known issue. 

I have actually been working on an update - I have refactored the post select UI to use the core data store instead. However this may also require some changes to your implementation. You can check out the branch here - https://github.com/humanmade/hm-gutenberg-tools/pull/34

**Comment by nicolairobles** [comment]
@mattheu there does seem to be some odd behavior happening with the refactored branch. 

Whereas before we had a PostControl like below that pulled in posts of the postType: "smart-list", the code in this branch just pulls in "posts". 

```
<PostControl
   label={ __( 'Select a List' ) }
   value={ [ listId ] }
   onChange={ posts => setAttributes( { listId: posts[0].id } ) }
   btnText={ __( 'Select Smart List' ) }
   postSelectProps={ { postType: 'smart-list' } }
/>
```
